version: '3.4'

# x-permission: &permission
#   user: UID_GID


services:
  gitlab-runner:
    container_name: gitlab-runner
    image: gitlab/gitlab-runner
    # <<: *permission
    ports:
      - 8093:8093
    # entrypoint: [] or file.sh
    # command: []
    volumes:
      - ./config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      HTTP_PROXY: http://proxy1.is.fujimic.com:8080
      http_proxy: http://proxy1.is.fujimic.com:8080
      HTTPS_PROXY: http://proxy1.is.fujimic.com:8080
      https_proxy: http://proxy1.is.fujimic.com:8080

# volumes:
# network: